// Data okupasi diesktrak dari Daftar-Okupasi-Asuransi-PAR-26012017.pdf
// (Lampiran I SEOJK No. 6/SEOJK.05/2017). Sumber arsip di apps/api/data/.
// parentCode = null untuk level 1 (kode kepala).

export interface OjkNode {
  code: string;
  name: string;
  level: number;
  parentCode: string | null;
}

export const OJK_DATA: OjkNode[] = [
  { code: '20', name: 'Mining (underground or above ground) of precious metal (Gold, Silver, Platinum and other precious metals) including primarily smelting and refining', level: 1, parentCode: null },
  { code: '21', name: 'Stone, gravel and sand extraction installations', level: 1, parentCode: null },
  { code: '22', name: 'Foil and sheet making plant, Forging Works, Locksmiths, Constructional Metalworks', level: 1, parentCode: null },
  { code: '23', name: 'Chemical products, pharmaceutical products', level: 1, parentCode: null },
  { code: '24', name: 'Spinning Mills, pre- spinning process', level: 1, parentCode: null },
  { code: '25', name: 'Wood pulp, cellulose based on wood pulp and linoleum factories', level: 1, parentCode: null },
  { code: '26', name: "Sawmills, carpenter's shops, parquet factories, sawing and cutting of firewood", level: 1, parentCode: null },
  { code: '27', name: 'Corn mills, paddy (rice), gambir', level: 1, parentCode: null },
  { code: '28', name: 'Hydro-electric power stations', level: 1, parentCode: null },
  { code: '29', name: 'Transport and traffic', level: 1, parentCode: null },
  { code: '30', name: 'Kina', level: 1, parentCode: null },
  { code: '31', name: 'Perkebunan serat,serat campuran dan kapok yang belum terproses', level: 1, parentCode: null },
  { code: '40', name: 'Bangunan di dalam lokasi perkebunan milik perorangan, selain proses produksi mengacu pada okupasi kebun kode 3XX', level: 1, parentCode: null },
  { code: '200', name: 'Mining (underground or above ground) of precious metal (Gold, Silver, Platinum and other precious metals) including primarily smelting and refining', level: 2, parentCode: '20' },
  { code: '201', name: 'Mining (underground or above ground) of Aluminium including Smelting and Refinery', level: 2, parentCode: '20' },
  { code: '202', name: 'Iron Mines, Blast Furnaces, Iron Foundries and Primary metal product', level: 2, parentCode: '20' },
  { code: '203', name: 'Steelworks and Rolling Mills, termasuk juga pembuatan besi dan baja paduan. Termasuk kegiatan tungku pembakar selain blast furnaces, steel converter, pabrik penggulungan dan finishing; produksi besi kasar dalam bentuk dasar seperti balok; produksi besi campuran.', level: 2, parentCode: '20' },
  { code: '204', name: 'Exploration and Production of Crude Petroleum and Natural Gas, Terminals, and geothermal', level: 2, parentCode: '20' },
  { code: '205', name: 'Mines, Other than Iron, Aluminium, Precious Metal, Salt', level: 2, parentCode: '20' },
  { code: '206', name: 'Foundries , Reduction Plants (Smelting and Refinery) for Metals (Excluding Iron, Alumunium and Precious Metal)', level: 2, parentCode: '20' },
  { code: '207', name: 'Coal and Lignite Extraction, Asphalt Mines', level: 2, parentCode: '20' },
  { code: '208', name: 'Salt mines', level: 2, parentCode: '20' },
  { code: '209', name: 'Peat extraction, Peat processing', level: 2, parentCode: '20' },
  { code: '210', name: 'Stone, gravel and sand extraction installations', level: 2, parentCode: '21' },
  { code: '211', name: 'Cement, Chalk, Lime and Gypsum Industry', level: 2, parentCode: '21' },
  { code: '212', name: 'Asbestos Products, Cut Stone and Stone products, (Animal) Bones and/or Shell crushing for feed, Mineral Wool', level: 2, parentCode: '21' },
  { code: '213', name: 'Brick and Structural Clay Tile, and structural Clay products (batubata, genteng, ubin)', level: 2, parentCode: '21' },
  { code: '214', name: 'Porcelain, Earthenware, Stoneware, Pottery, Clay Refractories, Ceramic Wall and tiles factory', level: 2, parentCode: '21' },
  { code: '215', name: 'Glass works, Glass blowing plants', level: 2, parentCode: '21' },
  { code: '216', name: 'Glass Products Made of Purchased Glass, lenses, safety glass, mirror', level: 2, parentCode: '21' },
  { code: '217', name: 'Precious stone workshops and processing plant', level: 2, parentCode: '21' },
  { code: '218', name: 'Emery and abrasive materials factories', level: 2, parentCode: '21' },
  { code: '219', name: 'Tarcoated chippings manufacture, asphalt and roofing felt factories, Asphalt Goods', level: 2, parentCode: '21' },
  { code: '220', name: 'Foil and sheet making plant, Forging Works, Locksmiths, Constructional Metalworks', level: 2, parentCode: '22' },
  { code: '221', name: 'Industrial, Mining and Commercial Machinery, Metal Coating Services, Coating Processes Using Flammable Materials including dipping and spray painting', level: 2, parentCode: '22' },
  { code: '222', name: 'Manufacture of electrical apparatus, Wet & dry batteries, Measuring and Precision apparatus photographic apparatus, Scientific laboratories', level: 2, parentCode: '22' },
  { code: '223', name: 'Cable and wire factories', level: 2, parentCode: '22' },
  { code: '224', name: 'Vehicle, Railways carriage and locomotive, Aircraft, Ships construction and assembling plants', level: 2, parentCode: '22' },
  { code: '225', name: 'Manufacture and or assembly of telecommunication or computer apparatus and Integrated circuits (IC)', level: 2, parentCode: '22' },
  { code: '226', name: 'Radio and Television Receiver factories, and or assembling plant, audio and audio-video recorder and or player factories and or assembling plants, manufacture of parts for radio and television receivers, audio and audio-video recorders and or players', level: 2, parentCode: '22' },
  { code: '227', name: 'Light Bulb Factories, Manufacture of Electronic Tubes and Fluorescent Tubes, Neon Signs, LED', level: 2, parentCode: '22' },
  { code: '228', name: 'Watches and clocks and their component parts factories', level: 2, parentCode: '22' },
  { code: '229', name: 'Metal jewelry and precious metal goods factories/diamond polishing factories', level: 2, parentCode: '22' },
  { code: '230', name: 'Chemical products, pharmaceutical products', level: 2, parentCode: '23' },
  { code: '231', name: 'Oil Processing', level: 2, parentCode: '23' },
  { code: '232', name: 'Petrochemical works', level: 2, parentCode: '23' },
  { code: '233', name: 'Storage Tanks (non terminal)', level: 2, parentCode: '23' },
  { code: '234', name: 'Manufacturer of plastic articles, Foam plastic, Synthetics resin', level: 2, parentCode: '23' },
  { code: '235', name: 'Manufacture of Artificial Fibres (Petrochemical Feedstock Process), Establishments primarily engaged in the manufacture of cellulosic fibers, such as rayon, viscose, cellulose acetate, cigarette tow, nitrocellulose fibers, etc, in the form of monofilament, yarn, staple or tow suitable for further manufacturing on spindles, looms, knitting machines or other textile processing equipment.', level: 2, parentCode: '23' },
  { code: '236', name: 'Manufacture of film, photographic paper, magnetic tape and celluloid batch adhesive tape (selotip)', level: 2, parentCode: '23' },
  { code: '237', name: 'Manufacture of tooth paste, soap, detergents, polishes, etheric oils, essences, parfumes, and cosmetic products, gelatine non-synthetic adhesives, starches, candles and wax goods, natural resins', level: 2, parentCode: '23' },
  { code: '238', name: 'Chemical fertilizer factories (conventional)', level: 2, parentCode: '23' },
  { code: '239', name: 'Powders, explosives, matches and firework factories', level: 2, parentCode: '23' },
  { code: '240', name: 'Spinning Mills, pre- spinning process', level: 2, parentCode: '24' },
  { code: '241', name: 'Weaving, pre-weaving process', level: 2, parentCode: '24' },
  { code: '242', name: 'Dressing (including but not limited to printing) and finishing', level: 2, parentCode: '24' },
  { code: '243', name: 'Mixed processes (Spinning, Weaving, Dressing and Finishing)', level: 2, parentCode: '24' },
  { code: '244', name: 'Processing of textile waste and non woven process', level: 2, parentCode: '24' },
  { code: '245', name: 'Ropemakers, stringmakers, sackmakers, blankets weaving mills, carpet manufacturer', level: 2, parentCode: '24' },
  { code: '246', name: 'Knitting mills, knitwear factories, stocking factories, glove factories hosiery mills, lamp wick factories, clothing and underwear manufacturers, sewing works, furrires, skin processing works, custom tailors, umbrella factories, felt goods factories, lace', level: 2, parentCode: '24' },
  { code: '247', name: "Upholstery, cushion maker’s and saddler's workshops", level: 2, parentCode: '24' },
  { code: '248', name: 'Cotton wool and capoc factories', level: 2, parentCode: '24' },
  { code: '249', name: 'Laundries, pressers, dry- (chemical) cleaning, cleaning of feathers and down', level: 2, parentCode: '24' },
  { code: '250', name: 'Wood pulp, cellulose based on wood pulp and linoleum factories', level: 2, parentCode: '25' },
  { code: '251', name: 'Paper, cardboard and hardboard factories', level: 2, parentCode: '25' },
  { code: '252', name: 'Cartoon and paper goods factories, bookbinders', level: 2, parentCode: '25' },
  { code: '253', name: 'Newspaper printers, other printers, art printing works, lithographers, screen printing on paper (sablon), typeplate workshops, block workshops, photogravure workshops', level: 2, parentCode: '25' },
  { code: '254', name: 'Coloured paper and/or wallpaper printing works', level: 2, parentCode: '25' },
  { code: '255', name: 'Straw and rush goods factories', level: 2, parentCode: '25' },
  { code: '256', name: 'Leather production and tanneries', level: 2, parentCode: '25' },
  { code: '257', name: 'Shoe factories', level: 2, parentCode: '25' },
  { code: '258', name: 'Leather goods factories', level: 2, parentCode: '25' },
  { code: '259', name: 'Rubber goods factories, foamed rubber factories, tyre factories, vulcanizing works, rubber factories (non estate risk), tyre cord manufacturers', level: 2, parentCode: '25' },
  { code: '260', name: "Sawmills, carpenter's shops, parquet factories, sawing and cutting of firewood", level: 2, parentCode: '26' },
  { code: '261', name: 'Furniture manufacture, cabinet makers, wooden boat builders, bamboo, rattan and wooden carvings and handicrafts', level: 2, parentCode: '26' },
  { code: '262', name: 'Manufacture of wood fibre board, hardboard masonite, wood chipboard, particle board, pressed wood and plywood, veneers', level: 2, parentCode: '26' },
  { code: '263', name: "Turner's shop, coachbuilder's shop, pipes, walking-sticks and picture frame factories, pencil factories", level: 2, parentCode: '26' },
  { code: '264', name: 'Wicker - Work Factories (anyaman bambu)', level: 2, parentCode: '26' },
  { code: '265', name: 'Cork goods factories such as shuttle cock factories', level: 2, parentCode: '26' },
  { code: '266', name: 'Broom, brush and paintbrush factories', level: 2, parentCode: '26' },
  { code: '267', name: 'Timber impregnation installations, plywood coating installation', level: 2, parentCode: '26' },
  { code: '268', name: 'Wooden musical instruments factories', level: 2, parentCode: '26' },
  { code: '269', name: 'Charcoal producers and other industries in main category 26', level: 2, parentCode: '26' },
  { code: '270', name: 'Corn mills, paddy (rice), gambir', level: 2, parentCode: '27' },
  { code: '271', name: 'Sugar mills, chocolate factories, sweets factories', level: 2, parentCode: '27' },
  { code: '272', name: 'Food paste producers, bakeries, processed food factories', level: 2, parentCode: '27' },
  { code: '273', name: 'Preserves factories (jams etc), pabrik sari gula, monosodium glutamate (MSG) producers, meat, meat products and fish product factories', level: 2, parentCode: '27' },
  { code: '274', name: 'Edible fats, edible oil and desiccated coconut producers', level: 2, parentCode: '27' },
  { code: '275', name: 'Dairy Product', level: 2, parentCode: '27' },
  { code: '276', name: 'Coffee roasting plants and coffee extract factories, malting', level: 2, parentCode: '27' },
  { code: '277', name: 'Cold stores, ice factories, abattoirs, butchers drying installation', level: 2, parentCode: '27' },
  { code: '278', name: 'Breweries, beverage producers, spirits, liquors producers, distilleries and vinegar Factories.', level: 2, parentCode: '27' },
  { code: '279', name: 'Tobacco, cigars and cigarettes manufacture', level: 2, parentCode: '27' },
  { code: '280', name: 'Hydro-electric power stations', level: 2, parentCode: '28' },
  { code: '281', name: 'Conventional power station, buildings with boiler houses and steam houses', level: 2, parentCode: '28' },
  { code: '282', name: 'Nuclear power stations', level: 2, parentCode: '28' },
  { code: '283', name: 'Overhead power transmission lines and networks', level: 2, parentCode: '28' },
  { code: '284', name: 'Voltage and current transformer stations, junction installation in the open', level: 2, parentCode: '28' },
  { code: '285', name: 'Rubbish incineration installations for power generation and heating', level: 2, parentCode: '28' },
  { code: '287', name: 'Waterworks, Pumping Stations, Sewage Works, Ice Rinks, Water treatment plant (WTP), WWTP) (including Underground Pipes)', level: 2, parentCode: '28' },
  { code: '290', name: 'Transport and traffic', level: 2, parentCode: '29' },
  { code: '291', name: 'Construction firms', level: 2, parentCode: '29' },
  { code: '292', name: 'Mass communication', level: 2, parentCode: '29' },
  { code: '293', name: 'Trading and storage', level: 2, parentCode: '29' },
  { code: '294', name: 'Hotels, Entertainment, Sport, Services', level: 2, parentCode: '29' },
  { code: '295', name: 'The caring services', level: 2, parentCode: '29' },
  { code: '296', name: 'Motor vehicle repair shops, services station and pools', level: 2, parentCode: '29' },
  { code: '297', name: 'Private Building', level: 2, parentCode: '29' },
  { code: '298', name: 'Property of public bodies', level: 2, parentCode: '29' },
  { code: '299', name: 'Special covers for building', level: 2, parentCode: '29' },
  { code: '300', name: 'Kina', level: 2, parentCode: '30' },
  { code: '301', name: 'Coklat', level: 2, parentCode: '30' },
  { code: '303', name: 'Kopi', level: 2, parentCode: '30' },
  { code: '304', name: 'The', level: 2, parentCode: '30' },
  { code: '305', name: 'Minyak sereh', level: 2, parentCode: '30' },
  { code: '306', name: 'Kapok (dari hasil buah)', level: 2, parentCode: '30' },
  { code: '307', name: 'Kelapa dan kopra', level: 2, parentCode: '30' },
  { code: '308', name: 'Karet (Gutta percha)', level: 2, parentCode: '30' },
  { code: '309', name: 'Gula bibit', level: 2, parentCode: '30' },
  { code: '310', name: 'Perkebunan serat,serat campuran dan kapok yang belum terproses', level: 2, parentCode: '31' },
  { code: '311', name: 'Pabrik tapioka di perkebunan', level: 2, parentCode: '31' },
  { code: '312', name: 'Damar dan terpentin', level: 2, parentCode: '31' },
  { code: '313', name: 'Cengkeh dan rempah- rempah', level: 2, parentCode: '31' },
  { code: '314', name: 'Padi, tanpa pengerjaan termasuk padi di tempat terbuka', level: 2, parentCode: '31' },
  { code: '315', name: 'Hortikultura,sayur- sayuran,kentang dan tidak ada pengeringan', level: 2, parentCode: '31' },
  { code: '316', name: 'Kelapa sawit', level: 2, parentCode: '31' },
  { code: '317', name: 'Tembakau', level: 2, parentCode: '31' },
  { code: '318', name: 'Gambir, barang-barang ditempat terbuka', level: 2, parentCode: '31' },
  { code: '2020', name: 'Iron Mines (underground or above ground)', level: 3, parentCode: '202' },
  { code: '2021', name: 'Blast Furnaces and Iron Foundries, kegiatan pengubahan seperti reduksi bijih besi dalam tungku pembakar dan oxygen converter.', level: 3, parentCode: '202' },
  { code: '2041', name: 'Exploration and Production for Crude Petroleum, on shore only', level: 3, parentCode: '204' },
  { code: '2042', name: 'Crude Petroleum Pipe Lines including pump station, on shore only', level: 3, parentCode: '204' },
  { code: '2043', name: 'Exploration and Production for Natural gas and geothermal, on shore', level: 3, parentCode: '204' },
  { code: '2044', name: 'Natural Gas Transmission and distribution including geothermal (including pipelines and pump stations), on shore only', level: 3, parentCode: '204' },
  { code: '2045', name: 'Terminal for crude oil', level: 3, parentCode: '204' },
  { code: '2046', name: 'Terminals for Liquefied Gases', level: 3, parentCode: '204' },
  { code: '2047', name: 'Other petroleum and gas products', level: 3, parentCode: '204' },
  { code: '2048', name: 'Degasification Stations', level: 3, parentCode: '204' },
  { code: '2049', name: 'Off shore Facilities', level: 3, parentCode: '204' },
  { code: '2051', name: 'Extraction and Processing above Ground', level: 3, parentCode: '205' },
  { code: '2052', name: 'Extraction and Processing below Ground', level: 3, parentCode: '205' },
  { code: '2058', name: 'Other and /or Mixed', level: 3, parentCode: '205' },
  { code: '2071', name: 'Extraction and Processing of Coal and Lignite above Ground (surface)', level: 3, parentCode: '207' },
  { code: '2072', name: 'Extraction and Processing of Coal and Lignite below Ground', level: 3, parentCode: '207' },
  { code: '2073', name: 'Coal Coking Plants (kokas)', level: 3, parentCode: '207' },
  { code: '2074', name: 'Manufacturing of Coal Briquettes', level: 3, parentCode: '207' },
  { code: '2081', name: 'Salt mines, extraction from rock or evaporated deposit', level: 3, parentCode: '208' },
  { code: '2082', name: 'Salt extraction from sea water (tambak garam)', level: 3, parentCode: '208' },
  { code: '21121', name: 'Cement Factories with rotary kiln', level: 3, parentCode: '211' },
  { code: '21122', name: 'Cement Factories without rotary kiln', level: 3, parentCode: '211' },
  { code: '2113', name: 'Concrete product, Ready Mixed Concrete, Unfired Stoneware, Industri beton, barang-barang dari batu buatan atau semen yang digunakan dalam konstruksi, seperti ubin, batu bata, papan, lembaran, panel, pipa, tonggak dan sebagainya. Industri mortar bubuk. Industri beton, dry mixed dan mortar siap pakai. Industri barang-barang gips yang digunakan dalam konstruksi, seperti papan, lembaran, panel.', level: 3, parentCode: '211' },
  { code: '2114', name: 'Artificial Teeth, non plastic', level: 3, parentCode: '211' },
  { code: '2121', name: 'Asbestos products, Cut stone and stone products', level: 3, parentCode: '212' },
  { code: '2122', name: 'Animal Bones and/or shell crushing for feed', level: 3, parentCode: '212' },
  { code: '2123', name: 'Mineral Wool', level: 3, parentCode: '212' },
  { code: '2131', name: 'Factories which only have Tunnel Kilns', level: 3, parentCode: '213' },
  { code: '2132', name: 'Factories which other types of Kilns', level: 3, parentCode: '213' },
  { code: '2133', name: 'Ceramic Color, Ceramic Frit, Glass Enamel Color, Inorganic Pigments', level: 3, parentCode: '213' },
  { code: '2141', name: 'Factories which only have Tunnel Kilns', level: 3, parentCode: '214' },
  { code: '2142', name: 'Factories with other kiln', level: 3, parentCode: '214' },
  { code: '2151', name: 'Glass container, Pressed and Blown Glass and Glassware', level: 3, parentCode: '215' },
  { code: '2152', name: 'Flat Glass including tempered', level: 3, parentCode: '215' },
  { code: '2158', name: 'Mixed', level: 3, parentCode: '215' },
  { code: '2201', name: 'Sheet rolling mills and foil making plants, forging works, locksmiths, constructional metal works, insulating pipes or metal', level: 3, parentCode: '220' },
  { code: '2202', name: 'Metal product from metal powder, industri penempaan, pengepresan, pencetakan dan pembentukan logam dengan metalurgi bubuk', level: 3, parentCode: '220' },
  { code: '2203', name: 'Mixed', level: 3, parentCode: '220' },
  { code: '2211', name: 'Industrial, Mining and Commercial Machinery', level: 3, parentCode: '221' },
  { code: '2212', name: 'Metal Coating Services (enameling, zincing, galvanizing, anodizing)', level: 3, parentCode: '221' },
  { code: '2213', name: 'Coating Processes Using Flammable Materials including dipping and spray painting services', level: 3, parentCode: '221' },
  { code: '2214', name: 'Metal/Steel Furniture factories (where plastic and foam is utilized) plastic cupboards and foldable chair factories', level: 3, parentCode: '221' },
  { code: '2215', name: 'Metal / Steel Spring Mattresses Manufacturing (without foam)', level: 3, parentCode: '221' },
  { code: '2218', name: 'Mixed', level: 3, parentCode: '221' },
  { code: '2221', name: 'Manufacture assembly and repair of electrical machines and apparatus', level: 3, parentCode: '222' },
  { code: '2222', name: 'Wet and dry battery factories', level: 3, parentCode: '222' },
  { code: '2223', name: 'Manufacture of measuring equipment photographic apparatus precision instrument, and scientific laboratories', level: 3, parentCode: '222' },
  { code: '2228', name: 'Mixed', level: 3, parentCode: '222' },
  { code: '2231', name: 'Wire factories', level: 3, parentCode: '223' },
  { code: '2232', name: 'Cable factories', level: 3, parentCode: '223' },
  { code: '2233', name: 'Nails, screws, bolts and nuts factories', level: 3, parentCode: '223' },
  { code: '2238', name: 'Mixed', level: 3, parentCode: '223' },
  { code: '2241', name: 'Vehicle construction plants including bicycle and becak (three wheels)', level: 3, parentCode: '224' },
  { code: '2242', name: 'Construction of railway carriages and locomotives', level: 3, parentCode: '224' },
  { code: '2243', name: 'Aircraft construction plants', level: 3, parentCode: '224' },
  { code: '2244', name: 'Ship construction, naval shipyards', level: 3, parentCode: '224' },
  { code: '2245', name: 'Vehicle assembling plants', level: 3, parentCode: '224' },
  { code: '2248', name: 'Mixed', level: 3, parentCode: '224' },
  { code: '2251', name: 'Manufacture and or assembly of telecommunication apparatus', level: 3, parentCode: '225' },
  { code: '2252', name: 'Manufacture and or assembly of computer apparatus', level: 3, parentCode: '225' },
  { code: '2253', name: 'Manufacture of Integrated Circuit (IC) from Chips', level: 3, parentCode: '225' },
  { code: '2261', name: 'Radio and television receiver factories and or assembling plants, audio video recorder and or player factories and or assembling plants', level: 3, parentCode: '226' },
  { code: '2262', name: 'Factories of parts for radio and television receivers, audio and audio-video recorders and players', level: 3, parentCode: '226' },
  { code: '2299', name: 'Other industries in main category 22', level: 3, parentCode: '229' },
  { code: '2300', name: 'Chemical products, pharmaceutical products', level: 3, parentCode: '230' },
  { code: '23010', name: 'Others than 23006 – 23009', level: 3, parentCode: '230' },
  { code: '23012', name: 'Ink Factory', level: 3, parentCode: '230' },
  { code: '2310', name: 'Oil Refinery, establishments primarily engaged in producing gasoline, kerosene, distillate fuel oils, residual fuel oils and through fractionation or straight distillation of crude oil, re-distillation of unfinished petroleum derivatives, cracking or other processes. Refinery products and byproducts typically include alkylates; asphalts; bitumens; benzene; butadiene; butylenes; ethylene; jet aircraft fuels; mineral jelly, oils and waxes; naphtha; naphthenic acids; paraffin wax; propylene; refinery gas; solvents; tar; biofuel', level: 3, parentCode: '231' },
  { code: '2311', name: 'Other Chemical and physical treatments e.g washing, desalinating, etc', level: 3, parentCode: '231' },
  { code: '2321', name: 'Primary Petrochemical Works with Basic Materials such as Ethylene, Methanol, Propylene, Butadiene, Benzene, Toluene, Xylene, producing formaldehyde, Acetic acid, ethanol, ethylene, oxide, ethylene dichloride, polyethylene, ethylbenzene, cumene, polypropylene, isopropanol, propylene oxide, cyclohexane', level: 3, parentCode: '232' },
  { code: '2322', name: 'Petrochemical Intermediate Products (Vinyl Chloride Monomer and Other than 2321)', level: 3, parentCode: '232' },
  { code: '2323', name: 'Polymerization on a Large Scale including manufacture of PP, PET, PE, ABS, PU, PIR, PS, PVC, Teflon, silicones, etc', level: 3, parentCode: '232' },
  { code: '2324', name: 'Fertilizer factories on petrochemical basis', level: 3, parentCode: '232' },
  { code: '2325', name: 'Synthetic rubber', level: 3, parentCode: '232' },
  { code: '2326', name: 'Liquefaction of natural gas', level: 3, parentCode: '232' },
  { code: '2327', name: 'Liquefaction of petroleum gases', level: 3, parentCode: '232' },
  { code: '2328', name: 'Petrol coke, soot, graphite', level: 3, parentCode: '232' },
  { code: '2329', name: 'Liquefaction and gasification of coal', level: 3, parentCode: '232' },
  { code: '2331', name: 'Crude Oil (non terminal)', level: 3, parentCode: '233' },
  { code: '2332', name: 'Oil Products in Tanks located in the Harbour Area (non terminal)', level: 3, parentCode: '233' },
  { code: '2333', name: 'Liquefied Gases (non terminal)', level: 3, parentCode: '233' },
  { code: '2334', name: 'Pipeline for chemical products', level: 3, parentCode: '233' },
  { code: '2335', name: 'Other liquid chemicals (e.g ammonia)', level: 3, parentCode: '233' },
  { code: '2341', name: 'Manufacture of Plastic product by extrusions, compression, transfer molding, injection molding, blow molding, blow stretch molding, etc', level: 3, parentCode: '234' },
  { code: '2342', name: 'Manufacture and processing of foam and expanded plastics', level: 3, parentCode: '234' },
  { code: '2343', name: 'Manufacturer of synthetic adhesive also called synthetic resin adhesive', level: 3, parentCode: '234' },
  { code: '2371', name: 'Manufacture of soaps, detergents and polishes', level: 3, parentCode: '237' },
  { code: '2372', name: 'Manufacture of etheric oils, essences, perfumes and cosmetic products', level: 3, parentCode: '237' },
  { code: '2373', name: 'Manufacture of gelatine, non-synthetic adhesives, starches, candles and wax goods, natural resins', level: 3, parentCode: '237' },
  { code: '2374', name: 'Manufacture of natural adhesives (glue) of organic origin coming from animal, vegetable or mineral source', level: 3, parentCode: '237' },
  { code: '2378', name: 'Mixed', level: 3, parentCode: '237' },
  { code: '2399', name: 'Powder, Explosives, Matches and Firework Factories', level: 3, parentCode: '239' },
  { code: '2401', name: 'Spinning mills, Pre- spinning : Animal Fibres', level: 3, parentCode: '240' },
  { code: '2402', name: 'Spinning mills, Pre- spinning : Vegetable and cellulose fibres', level: 3, parentCode: '240' },
  { code: '2403', name: 'Spinning mills, Pre- spinning : Synthetic fibres (mechanical process)', level: 3, parentCode: '240' },
  { code: '2408', name: 'Spinning mills,Pre- spinning : Mixed', level: 3, parentCode: '240' },
  { code: '2411', name: 'Weaving, Pre-Weaving Processes: Animal fibres', level: 3, parentCode: '241' },
  { code: '2412', name: 'Weaving, Pre-Weaving Processes: Vegetable and cellulose fibres', level: 3, parentCode: '241' },
  { code: '2413', name: 'Weaving, Pre-Weaving Processes: Synthetic fibres', level: 3, parentCode: '241' },
  { code: '2418', name: 'Weaving, Pre-Weaving Processes: Mixed', level: 3, parentCode: '241' },
  { code: '2421', name: 'Dressing and finishing processes : Animal Fibres', level: 3, parentCode: '242' },
  { code: '2422', name: 'Dressing and finishing processes : Vegetable and Cellulose Fibres', level: 3, parentCode: '242' },
  { code: '2423', name: 'Dressing and finishing processes : Synthetic Fibres', level: 3, parentCode: '242' },
  { code: '2428', name: 'Dressing and finishing processes : Mixed', level: 3, parentCode: '242' },
  { code: '2431', name: 'Mixed processes(spinning, weaving) :Animal fibres', level: 3, parentCode: '243' },
  { code: '2432', name: 'Mixed processes(spinning, weaving) : Vegetable and cellulose', level: 3, parentCode: '243' },
  { code: '2433', name: 'Mixed processes(spinning, weaving) : Synthetic fibres', level: 3, parentCode: '243' },
  { code: '2438', name: 'Mixed processes(spinning, weaving) : Mixed', level: 3, parentCode: '243' },
  { code: '2441', name: 'Processing of textile waste : Animal fibres', level: 3, parentCode: '244' },
  { code: '2442', name: 'Processing of textile waste : Vegetable and cellulose fibres', level: 3, parentCode: '244' },
  { code: '2443', name: 'Processing of textile waste : Synthetic fibres', level: 3, parentCode: '244' },
  { code: '2448', name: 'Processing of textile waste : Mixed', level: 3, parentCode: '244' },
  { code: '2451', name: 'Ropemakers, stringmakers and sackmakers', level: 3, parentCode: '245' },
  { code: '2452', name: 'Blanket waving mills and carpet manufacture', level: 3, parentCode: '245' },
  { code: '2458', name: 'Mixed', level: 3, parentCode: '245' },
  { code: '2461', name: 'Knitting mills, knitwear factories, stocking factories, hosiery mills, glove factories and lamp wick factories', level: 3, parentCode: '246' },
  { code: '2462', name: 'Clothing and underwear manufactures, sewing works, furriers, skin processing works, custom tailors (garment', level: 3, parentCode: '246' },
  { code: '2463', name: 'Umbrella factories, felt goods factories, lace factories, embroidery factories', level: 3, parentCode: '246' },
  { code: '2464', name: 'Batik Establishments', level: 3, parentCode: '246' },
  { code: '2465', name: 'Clothing, underwear, jacket, custom tailor and other garment product (konveksi) - small scale/home industry', level: 3, parentCode: '246' },
  { code: '2466', name: 'Zipper Factories', level: 3, parentCode: '246' },
  { code: '2468', name: 'Mixed', level: 3, parentCode: '246' },
  { code: '2491', name: 'Laundries and pressers', level: 3, parentCode: '249' },
  { code: '2492', name: 'Dry-(chemical) cleaning', level: 3, parentCode: '249' },
  { code: '2493', name: 'Cleaning of feathers and down', level: 3, parentCode: '249' },
  { code: '2498', name: 'Mixed', level: 3, parentCode: '249' },
  { code: '2501', name: 'Wood pulp and cellulose based on wood pulp', level: 3, parentCode: '250' },
  { code: '2502', name: 'Lino factories', level: 3, parentCode: '250' },
  { code: '2508', name: 'Mixed', level: 3, parentCode: '250' },
  { code: '2511', name: 'Paper manufacture', level: 3, parentCode: '251' },
  { code: '2512', name: 'Manufacture of cardboard and hardboard', level: 3, parentCode: '251' },
  { code: '2518', name: 'Mixed', level: 3, parentCode: '251' },
  { code: '2521', name: 'Carton Manufacture including corrugated paper product', level: 3, parentCode: '252' },
  { code: '2522', name: 'Paper goods and or carton goods factories', level: 3, parentCode: '252' },
  { code: '2523', name: 'Bookbinders', level: 3, parentCode: '252' },
  { code: '2528', name: 'Mixed', level: 3, parentCode: '252' },
  { code: '2531', name: 'Newspaper printers', level: 3, parentCode: '253' },
  { code: '2532', name: 'Other printers, art printing works, lithographers, sablon', level: 3, parentCode: '253' },
  { code: '2533', name: 'Typeplate workshops, block workshops', level: 3, parentCode: '253' },
  { code: '2534', name: 'Photogravure workshop', level: 3, parentCode: '253' },
  { code: '2538', name: 'Mixed', level: 3, parentCode: '253' },
  { code: '2571', name: 'Leather', level: 3, parentCode: '257' },
  { code: '2572', name: 'Rubber and/or Canvas', level: 3, parentCode: '257' },
  { code: '2578', name: 'Other materials or mixture of above mentioned materials and other materials', level: 3, parentCode: '257' },
  { code: '2581', name: 'Leather goods factories', level: 3, parentCode: '258' },
  { code: '2582', name: 'Imitation leather goods factories', level: 3, parentCode: '258' },
  { code: '2588', name: 'Mixed', level: 3, parentCode: '258' },
  { code: '2591', name: 'Rubber goods factories (excluding foamed rubber)', level: 3, parentCode: '259' },
  { code: '2592', name: 'Foamed rubber factories', level: 3, parentCode: '259' },
  { code: '2593', name: 'Tyre factories, vulcanizing works rubber factories (non estate risks)', level: 3, parentCode: '259' },
  { code: '2594', name: 'Remilling factories', level: 3, parentCode: '259' },
  { code: '2595', name: 'Smoke houses (rubber)', level: 3, parentCode: '259' },
  { code: '2596', name: 'Crumb Rubber Factories (natural and recycling)', level: 3, parentCode: '259' },
  { code: '2598', name: 'Mixed', level: 3, parentCode: '259' },
  { code: '2601', name: 'Sawmills, panglong (sawmills with manual manufacture only)', level: 3, parentCode: '260' },
  { code: '2602', name: "Carpenter's shops, parquet factories sawing and cutting of firewood", level: 3, parentCode: '260' },
  { code: '2603', name: 'Wooden sport equipment', level: 3, parentCode: '260' },
  { code: '2604', name: 'Obat nyamuk bakar/mosquito coil factories', level: 3, parentCode: '260' },
  { code: '2605', name: 'Toothpick, chopsticks factories', level: 3, parentCode: '260' },
  { code: '2606', name: 'Rattan drying & peeling mills', level: 3, parentCode: '260' },
  { code: '2608', name: 'Mixed', level: 3, parentCode: '260' },
  { code: '2621', name: 'Manufacture of fibreboard, hardboard, Masonite', level: 3, parentCode: '262' },
  { code: '2622', name: 'manufacture of wood chipboard, particle board, pressed wood', level: 3, parentCode: '262' },
  { code: '2623', name: 'Manufacture of plywood (triplex, multiplex) and veneer and blackboard, laminboard, fancy flooring and other related products provided carried out in the same (plywood) manufacture building using formaldehyde synthetic resin adhesives', level: 3, parentCode: '262' },
  { code: '2624', name: 'Sirap factories', level: 3, parentCode: '262' },
  { code: '2628', name: 'Mixed', level: 3, parentCode: '262' },
  { code: '2701', name: 'Corn mills', level: 3, parentCode: '270' },
  { code: '2702', name: 'Fodder mills', level: 3, parentCode: '270' },
  { code: '2703', name: 'Gaplek mills', level: 3, parentCode: '270' },
  { code: '2704', name: 'Gambir factories', level: 3, parentCode: '270' },
  { code: '2705', name: 'Flour Mills (tepung terigu, tepung tapioka, tepung sagu, tepung beras, etc)', level: 3, parentCode: '270' },
  { code: '2708', name: 'Mixed including feed mill', level: 3, parentCode: '270' },
  { code: '2709', name: 'Paddy & Hulling Mills', level: 3, parentCode: '270' },
  { code: '2711', name: 'Sugar mills, chocolate factories, sweets factories', level: 3, parentCode: '271' },
  { code: '2721', name: 'Alimentary Paste Producers (dried dough, pasta, macaroni, etc)', level: 3, parentCode: '272' },
  { code: '2722', name: 'Bakeries and biscuit works', level: 3, parentCode: '272' },
  { code: '2723', name: 'Processed food factories (bihun, mie, lomie, kerupuk) and the like', level: 3, parentCode: '272' },
  { code: '2728', name: 'Mixed', level: 3, parentCode: '272' },
  { code: '2731', name: 'Preserves Factories (Jam, fruit canning, etc.), Pabrik sari gula Monosodium Glutamate (MSG ) Producers', level: 3, parentCode: '273' },
  { code: '2732', name: 'Meat, meat products and fish products factories', level: 3, parentCode: '273' },
  { code: '2733', name: 'Soya bean, tomato and hot pepper sauce', level: 3, parentCode: '273' },
  { code: '2734', name: 'Poultry Farms', level: 3, parentCode: '273' },
  { code: '2735', name: 'Other farms', level: 3, parentCode: '273' },
  { code: '2736', name: 'Poultry Hatcheries', level: 3, parentCode: '273' },
  { code: '2737', name: 'Fish Hatcheries', level: 3, parentCode: '273' },
  { code: '2741', name: 'Edible fats producers', level: 3, parentCode: '274' },
  { code: '2742', name: 'Edible Oils Plants and Other Plants Producing Edible Palm Oil (CPO, PKO, CCO), cooking oil and margarine from vegetable oil or Other Edible Oils or Desiccated Coconut', level: 3, parentCode: '274' },
  { code: '2743', name: 'Storage of crude palm oil (CPO) outside estates including storage of edible oils in tanks', level: 3, parentCode: '274' },
  { code: '2748', name: 'Mixed', level: 3, parentCode: '274' },
  { code: '2751', name: 'Dairies and Dairy Products, including fresh milk, UHT milk, yogurt, ice cream, cheese, butter, etc', level: 3, parentCode: '275' },
  { code: '2752', name: 'Powder milk', level: 3, parentCode: '275' },
  { code: '2761', name: 'Coffee roasting plants and other roasting plants, coffee extract factories, coffee sorting and peeling establishments, cashew nut roasting and peeling plants', level: 3, parentCode: '276' },
  { code: '2762', name: 'Malting', level: 3, parentCode: '276' },
  { code: '2763', name: 'Tea Sheds and Tea Factories, including herb drink (serbat, etc)', level: 3, parentCode: '276' },
  { code: '2768', name: 'Mixed', level: 3, parentCode: '276' },
  { code: '2771', name: 'Cold stores and ice factories', level: 3, parentCode: '277' },
  { code: '2772', name: 'Abbatoirs and Butchers, including slaughter house', level: 3, parentCode: '277' },
  { code: '2773', name: 'Drying installations', level: 3, parentCode: '277' },
  { code: '2778', name: 'Mixed', level: 3, parentCode: '277' },
  { code: '2781', name: 'Breweries, beer factory', level: 3, parentCode: '278' },
  { code: '2782', name: 'Producers of wines, fruit juices and mineral water', level: 3, parentCode: '278' },
  { code: '2783', name: 'Producers of Spirits and Liquors and Distilleries', level: 3, parentCode: '278' },
  { code: '2784', name: 'Vinegar factories (Acid liquor) factories', level: 3, parentCode: '278' },
  { code: '2788', name: 'Mixed', level: 3, parentCode: '278' },
  { code: '2790', name: 'Tobacco, cigars and cigarettes manufacture', level: 3, parentCode: '279' },
  { code: '2791', name: 'Drying Sheds / Smoke Houses for tobacco leaves Drying Shed / Smoke House is a place for the drying process of a Tobacco leaves by using naturally and heating process alternately', level: 3, parentCode: '279' },
  { code: '2792', name: 'Oven, is a place for the drying process of a Tobacco leaves by using heating process', level: 3, parentCode: '279' },
  { code: '2793', name: 'Tobacco Establishement (Usaha Pengolahan Tembakau) is a Company with an activity to process a Tobacco leaves received from the Farmers and will be proceed to be a Tobacco leaves which is ready for the export of to be used by Cigarrette Factories. The activity of this Tobacco Establishment covering Purchasing, Peeling, Fermenatasion, Packing and Storing Processes', level: 3, parentCode: '279' },
  { code: '2801', name: 'Conventional hydro electric power station', level: 3, parentCode: '280' },
  { code: '2802', name: 'Micro hydro electric power station', level: 3, parentCode: '280' },
  { code: '2811', name: 'PLTU', level: 3, parentCode: '281' },
  { code: '2812', name: 'PLTG', level: 3, parentCode: '281' },
  { code: '2813', name: 'PLTGU (combined cycle)', level: 3, parentCode: '281' },
  { code: '2814', name: 'PLTD', level: 3, parentCode: '281' },
  { code: '2815', name: 'Other', level: 3, parentCode: '281' },
  { code: '2901', name: 'Railways, LRT, MRT, Monorel, Cable cars (kereta gantung)', level: 3, parentCode: '290' },
  { code: '2902', name: 'Highways, bridges, airport runways', level: 3, parentCode: '290' },
  { code: '2903', name: 'Jetties (dermaga)', level: 3, parentCode: '290' },
  { code: '2904', name: 'Aerial railways/ropeways, funicular railways, chairlifts', level: 3, parentCode: '290' },
  { code: '2905', name: 'Airport : Hangars', level: 3, parentCode: '290' },
  { code: '2906', name: 'Airport : Workshops, spare parts depots', level: 3, parentCode: '290' },
  { code: '2907', name: 'Airport : Aircrafts', level: 3, parentCode: '290' },
  { code: '2908', name: 'Airport : General airport services', level: 3, parentCode: '290' },
  { code: '2909', name: 'Airport : Others', level: 3, parentCode: '290' },
  { code: '2911', name: 'Construction firm, road construction and construction sites', level: 3, parentCode: '291' },
  { code: '2912', name: 'Cranes, excavators, elevators, road building machines (excluding tar sprayers)', level: 3, parentCode: '291' },
  { code: '2913', name: 'Tar sprayers and road surfacing plants', level: 3, parentCode: '291' },
  { code: '2914', name: 'Others', level: 3, parentCode: '291' },
  { code: '2915', name: 'Welding Plants', level: 3, parentCode: '291' },
  { code: '2921', name: 'Film television and recording on magnetic tape studios', level: 3, parentCode: '292' },
  { code: '2922', name: 'Film reproduction (prints) and photo treatment', level: 3, parentCode: '292' },
  { code: '2923', name: 'Cinemas, assembly rooms and concert halls', level: 3, parentCode: '292' },
  { code: '2924', name: 'Theatres, variety theatres and circuses housed in permanent buildings', level: 3, parentCode: '292' },
  { code: '2925', name: 'Circuses with a big top, show and exhibition tents', level: 3, parentCode: '292' },
  { code: '2926', name: 'Others', level: 3, parentCode: '292' },
  { code: '2927', name: 'Radio broadcasting, television broadcasting & relay stations, transmission tower including microwave transmission tower and relay tower', level: 3, parentCode: '292' },
  { code: '2928', name: 'Sentral Telecommunication Otomat (STO) dan warung pos/telekomunikasi (wartel)', level: 3, parentCode: '292' },
  { code: '2929', name: 'Telecommunication operator engaged in furnishing telephone voice and data communication including their telephone transmission such as optical fiber and microwave or satellite facilities', level: 3, parentCode: '292' },
  { code: '2930', name: 'Drug Store (apotek)', level: 3, parentCode: '293' },
  { code: '29311', name: 'Department stores, building risk area > 200m2. If below 200m2 go to 2934', level: 3, parentCode: '293' },
  { code: '29312', name: 'Supermarket, building risk area > 200m2. If below 200m2 go to 2933', level: 3, parentCode: '293' },
  { code: '29314', name: 'Grocery Store', level: 3, parentCode: '293' },
  { code: '2932', name: 'Mail Order Houses, online shopping', level: 3, parentCode: '293' },
  { code: '2933', name: 'Chain Stores, convenience store, grocery store, with building risk area <200m2', level: 3, parentCode: '293' },
  { code: '2934', name: 'Shops, non chain store', level: 3, parentCode: '293' },
  { code: '2936', name: 'Others', level: 3, parentCode: '293' },
  { code: '2937', name: 'Private and public warehouse', level: 3, parentCode: '293' },
  { code: '2938', name: 'Storage tanks', level: 3, parentCode: '293' },
  { code: '2939', name: 'Miscellaneous (open storage)', level: 3, parentCode: '293' },
  { code: '2941', name: 'Hotels, motels, inns and the like', level: 3, parentCode: '294' },
  { code: '2942', name: 'Night clubs, dance halls, ball rooms, discotheques, bars, billiards karaoke', level: 3, parentCode: '294' },
  { code: '2943', name: 'Swimming pools or complex of swimming pools, sports stadium, sport centre, fitness centre, gyms and the like, private (member only) club houses and golf club', level: 3, parentCode: '294' },
  { code: '2944', name: 'Others', level: 3, parentCode: '294' },
  { code: '2945', name: 'Restaurants, eating and drinking places, (permanent building)', level: 3, parentCode: '294' },
  { code: '2946', name: 'Stalls, Huts ( Kedai ), Eating Places ( Warung Makan ), and the like (tenda, non permanent building)', level: 3, parentCode: '294' },
  { code: '2947', name: 'Beauty salon/ Hair dresser/ Barber shops', level: 3, parentCode: '294' },
  { code: '2949', name: 'Recreation areas and cultural centre', level: 3, parentCode: '294' },
  { code: '2951', name: "Sanatorium, hospitals, doctor's consulting rooms, old people's and children's homes", level: 3, parentCode: '295' },
  { code: '2952', name: 'Religious facilities such as mosques, temples, churches, convents and the like', level: 3, parentCode: '295' },
  { code: '2953', name: 'Schools, universities and training colleges', level: 3, parentCode: '295' },
  { code: '2954', name: 'Museums', level: 3, parentCode: '295' },
  { code: '2955', name: 'Psychiatric clinics', level: 3, parentCode: '295' },
  { code: '2961', name: 'Motor vehicle repair shops with facilities for body repair work (including welding/ soldering and spray painting) and service station (parts replacement, replacing/ topping up engine oil/ brake fluid, lubrication and engine/ body/ chassis scrubbing/ washing)', level: 3, parentCode: '296' },
  { code: '2962', name: 'Code 2961 and also operating a petrol/diesel fuel station within the premises', level: 3, parentCode: '296' },
  { code: '2963', name: 'Motor vehicle service stations only without bodyrepair etc., (refer to code 2961)', level: 3, parentCode: '296' },
  { code: '2964', name: 'Motor vehicle pools without any body repair', level: 3, parentCode: '296' },
  { code: '2965', name: 'Motor vehicle pools with service station facilities as described under code 2961', level: 3, parentCode: '296' },
  { code: '2966', name: 'Motor vehicle pools with body repair work and service station facilities as described under code 2961', level: 3, parentCode: '296' },
  { code: '2967', name: 'Motor vehicle pools with a petrol/diesel fuel station within the premises', level: 3, parentCode: '296' },
  { code: '2968', name: 'Motor vehicle pools with body repair work & service station facilities as described under code 2961 and also operating a petrol/diesel fuel station within the premises', level: 3, parentCode: '296' },
  { code: '2969', name: 'Rust protection / paint protection workshops', level: 3, parentCode: '296' },
  { code: '2971', name: 'Apartments/ condominiums, offices, multi-storeyed car parks not exceeding 6 storeys above ground level', level: 3, parentCode: '297' },
  { code: '2972', name: 'Apartments/ condominiums, offices, multi-storeyed car parks exceeding 6 storeys up to 18 storeys above ground level', level: 3, parentCode: '297' },
  { code: '2973', name: 'Apartments/ condominiums, offices, multi-storeyed car parks exceeding 18 storeys above ground level', level: 3, parentCode: '297' },
  { code: '2974', name: 'Convention halls and other multi purpose buildings (but excluding exhibition)', level: 3, parentCode: '297' },
  { code: '2975', name: 'Apartments/ condominiums, offices, multi-storeyed car parks - exceeding 24 storeys above ground', level: 3, parentCode: '297' },
  { code: '2976', name: 'Dwelling houses not classified as shop houses (ruko) not exceeding 3 storeys', level: 3, parentCode: '297' },
  { code: '2977', name: 'Dwelling houses buildings floating on the river/sea shore (regardless of constructional class)', level: 3, parentCode: '297' },
  { code: '2978', name: 'Independent analytical laboratories', level: 3, parentCode: '297' },
  { code: '2981', name: 'Public buildings', level: 3, parentCode: '298' },
  { code: '2982', name: 'Police barracks and police stations', level: 3, parentCode: '298' },
  { code: '2983', name: 'Military Barracks', level: 3, parentCode: '298' },
  { code: '2984', name: 'Others', level: 3, parentCode: '298' },
  { code: '2991', name: 'Buildings in course of construction (rate to be applied againts Full Value of completed building)', level: 3, parentCode: '299' },
  { code: '2992', name: 'Rents', level: 3, parentCode: '299' },
  { code: '3031', name: 'Kopi tanpa rumah pengeringan', level: 3, parentCode: '303' },
  { code: '3032', name: 'Dengan rumah pengeringan', level: 3, parentCode: '303' },
  { code: '3071', name: 'Tanpa ekstraksi Minyak', level: 3, parentCode: '307' },
  { code: '3072', name: 'Dengan ekstraksi Minyak', level: 3, parentCode: '307' },
  { code: '3073', name: 'Gedung pengeringan dengan pengering buatan', level: 3, parentCode: '307' },
  { code: '3081', name: 'Gedung tidak termasuk rumah asap', level: 3, parentCode: '308' },
  { code: '3082', name: 'Rumah Asap', level: 3, parentCode: '308' },
  { code: '22111', name: 'Industrial, Mining and Commercial Machinery, without melting of metal', level: 4, parentCode: '2211' },
  { code: '22112', name: 'Industrial, Mining and Commercial Machinery with melting of metal', level: 4, parentCode: '2211' },
  { code: '23001', name: 'General Chemical Products Factories, including biofuel from vegetable oil and oleochemical', level: 4, parentCode: '2300' },
  { code: '23002', name: 'Pharmaceutical Products Factories and Medicated Plaster', level: 4, parentCode: '2300' },
  { code: '23003', name: 'Natural Drug (Jamu)', level: 4, parentCode: '2300' },
  { code: '23004', name: 'Pesticides and agricultural chemical', level: 4, parentCode: '2300' },
  { code: '23005', name: 'Paint & Varnish', level: 4, parentCode: '2300' },
  { code: '23006', name: 'Acid, Alkaline Factories', level: 4, parentCode: '2300' },
  { code: '23007', name: 'Chlor - Alkali Electrolysis', level: 4, parentCode: '2300' },
  { code: '23008', name: 'Air Separation Plants (production of Technical Gases,e.g. Oxygen, Nitrogen, Hydrogen)', level: 4, parentCode: '2300' },
  { code: '23009', name: 'Peroxide Manufacture, Application and Storage', level: 4, parentCode: '2300' },
  { code: '230121', name: 'Ink factories - solvent base', level: 4, parentCode: '23012' },
  { code: '230122', name: 'Ink factories - water base', level: 4, parentCode: '23012' },
  { code: '23111', name: 'Hydrogen Generation from Natural Gas, Refinery Gas, or Liquid', level: 4, parentCode: '2311' },
  { code: '23115', name: 'Lubricating oils and greases by blending and compounding purchased materials including re- used oil processing', level: 4, parentCode: '2311' },
  { code: '23241', name: 'Ammonia Production and/or Urea Production', level: 4, parentCode: '2324' },
  { code: '23242', name: 'Production of Melamine Powder/Melamine Crystal using Urea Solution and Ammonia Gas', level: 4, parentCode: '2324' },
  { code: '23431', name: 'Using Inflammable / Combustible / Volatile Liquids and or Solids at anytime during the production process', level: 4, parentCode: '2343' },
  { code: '23432', name: 'Using Liquid Methanol, Water and Air in a continuous process to produce Formaldehyde Gas thence Formaldehyde Solution in Water (Formalin) and then by mixing with either Urea, Phenol, Melamine, or Resorcinol in batch produce the related Formaldehyde Resin Adhesives', level: 4, parentCode: '2343' },
  { code: '23741', name: 'water based', level: 4, parentCode: '2374' },
  { code: '23742', name: 'solvent based', level: 4, parentCode: '2374' },
  { code: '25931', name: 'Tyre Cord Manufacturers (using Tyre Yarn as basic Material)', level: 4, parentCode: '2593' },
  { code: '27111', name: 'sugar refinery plant', level: 4, parentCode: '2711' },
  { code: '27112', name: 'cane sugar plant', level: 4, parentCode: '2711' },
  { code: '27113', name: 'Chocolate and Sweets Factories', level: 4, parentCode: '2711' },
  { code: '27831', name: 'Producers of Spirits and Liquors', level: 4, parentCode: '2783' },
  { code: '27832', name: 'Distilleries producing Alcohol (Ethanol) for Nutrional Purposes from Non - Petrochemical Materials. For Producers of Alcohol (Ethanol) from Petrochemical Materials see Code No. 2321: Petrochemical', level: 4, parentCode: '2783' },
  { code: '28111', name: 'PLTU using steam boiler', level: 4, parentCode: '2811' },
  { code: '28112', name: 'PLTU using Geothermal', level: 4, parentCode: '2811' },
  { code: '29291', name: 'Data center', level: 4, parentCode: '2929' },
  { code: '29371', name: 'Private Warehouses, dengan syarat sebagai berikut : 1. Gudang yang disewa oleh tertanggung secara langsung dari pemilik gudang atau pemilik bangunan/tempat penimbunan 2. Gudang yang dimiliki oleh tertanggung atau disewa oleh tertanggung tersebut pada no. 1 diatas yang secara khusus dipergunakan untuk menimbun barang-barang yang seluruhnya menjadi milik/kepentingan', level: 4, parentCode: '2937' },
  { code: '29378', name: 'Public Warehouses, dengan syarat selain disebutkan di 29371', level: 4, parentCode: '2937' },
  { code: '29383', name: 'Petrol / Diesel Fuel Stations', level: 4, parentCode: '2938' },
  { code: '29384', name: 'Liquid Nature Gas (LNG) Stations for Automobiles', level: 4, parentCode: '2938' },
  { code: '29385', name: 'Others', level: 4, parentCode: '2938' },
  { code: '29394', name: 'Bonded Warehouses', level: 4, parentCode: '2939' },
  { code: '29395', name: 'Show Rooms ( Permanent Show Rooms without Repair / Workshop ) for New Motor Cars, Electronic Goods, Machinery, Office and Medical Equipment and the like New Motor Cars, Electronic Goods, Machinery, Office and Medical Equipment and the like', level: 4, parentCode: '2939' },
  { code: '29411', name: 'certified below 3 star classification', level: 4, parentCode: '2941' },
  { code: '29412', name: 'certified as 3 star and above', level: 4, parentCode: '2941' },
  { code: '29431', name: 'Swimming Pools or Complex of Swimming Pools not forming part of Recreation Centre or Hotel Complex such as waterpark', level: 4, parentCode: '2943' },
  { code: '29432', name: 'Sport Stadium, Sport Centres, Fitness Centres, Gymns and the like', level: 4, parentCode: '2943' },
  { code: '29433', name: 'Private ( member only ) Club House and Golf Club Houses', level: 4, parentCode: '2943' },
  { code: '29761', name: 'Dwelling house for boarding house/kos- kosan', level: 4, parentCode: '2976' },
  { code: '230011', name: 'General Chemical Products Factories flammable, including biofuel from vegetable oil and oleochemical', level: 5, parentCode: '23001' },
  { code: '230012', name: 'General Chemical Products Factories non flammable', level: 5, parentCode: '23001' },
  { code: '230051', name: 'Solvent base product', level: 5, parentCode: '23005' },
  { code: '230052', name: 'Water base product', level: 5, parentCode: '23005' },
];

// total: 467 node (level 1: 13, level 2: 115, level 3+: 339)
